services:
  db:
    image: postgres:16-alpine
    container_name: escaperoom_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: escaperoom
      POSTGRES_PASSWORD: escaperoom
      POSTGRES_DB: escaperoom
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
