// Banco de perguntas do Mapa de Hardware (6º ao 9º ano).
//
// Cada componente tem perguntas de dificuldade 1 (aquecimento) a 5 (desafio)
// e de tipos variados. O motor adaptativo escolhe a dificuldade de acordo com
// o desempenho do aluno, e cada tipo sorteia variações (alternativas,
// afirmações, pares, números) para que a resposta não fique sempre no mesmo
// lugar nem seja igual para todo mundo.
//
// `pesquise` é a dica de pesquisa (não entrega a resposta) e `porque` é a
// explicação mostrada depois que o aluno acerta.

const PERGUNTA_VF = 'Essa afirmação é verdadeira ou falsa?';

const mc = ({ d, pesquise, pergunta, certas, erradas, porque, quantidade, variantes }) => ({
  tipo: 'multipla_escolha',
  dificuldade: d,
  enunciado: pesquise,
  pergunta: pergunta || '',
  conteudo: { corretas: certas, incorretas: erradas, ...(quantidade && { quantidade }), ...(variantes && { variantes }) },
  explicacao: porque,
});

const vf = ({ d, pesquise, afirmacoes, porque }) => ({
  tipo: 'verdadeiro_falso',
  dificuldade: d,
  enunciado: pesquise,
  pergunta: PERGUNTA_VF,
  conteudo: { afirmacoes: afirmacoes.map(([texto, verdadeira]) => ({ texto, verdadeira })) },
  explicacao: porque,
});

const escrita = ({ d, pesquise, pergunta, aceitas, dica, porque }) => ({
  tipo: 'texto',
  dificuldade: d,
  enunciado: pesquise,
  pergunta,
  conteudo: { respostas: aceitas, ...(dica && { dica }) },
  explicacao: porque,
});

const slider = ({ d, pesquise, pergunta, min, max, passo, unidade, resposta, tolerancia, variantes, porque }) => ({
  tipo: 'numero',
  dificuldade: d,
  enunciado: pesquise,
  pergunta: pergunta || '',
  conteudo: { min, max, passo, unidade, resposta, ...(tolerancia && { tolerancia }), ...(variantes && { variantes }) },
  explicacao: porque,
});

const ordem = ({ d, pesquise, pergunta, itens, inicio, fim, porque }) => ({
  tipo: 'ordenar',
  dificuldade: d,
  enunciado: pesquise,
  pergunta,
  conteudo: { itens, rotuloInicio: inicio, rotuloFim: fim },
  explicacao: porque,
});

const anagrama = ({ d, pesquise, pergunta, palavra, dica, porque }) => ({
  tipo: 'anagrama',
  dificuldade: d,
  enunciado: pesquise,
  pergunta,
  conteudo: { palavra, ...(dica && { dica }) },
  explicacao: porque,
});

const pares = ({ d, pesquise, pergunta, lista, quantidade, porque }) => ({
  tipo: 'associar',
  dificuldade: d,
  enunciado: pesquise,
  pergunta,
  conteudo: { pares: lista.map(([a, b]) => ({ a, b })), ...(quantidade && { quantidade }) },
  explicacao: porque,
});

const BANCO_DE_QUESTOES = {
  // ======================= NÍVEL 1 — COMPONENTES BÁSICOS =======================

  'Placa-mãe': [
    anagrama({
      d: 1,
      pesquise: 'Pesquise como se chama a placa-mãe em inglês.',
      pergunta: 'Monte o nome da placa-mãe em inglês.',
      palavra: 'MOTHERBOARD',
      dica: '11 letras',
      porque: 'Motherboard é a placa-mãe: a placa principal onde todas as outras peças se encaixam.',
    }),
    mc({
      d: 2,
      pesquise: 'Pesquise para que serve a placa-mãe e com qual parte do corpo ela costuma ser comparada.',
      pergunta: 'Qual é o papel principal da placa-mãe?',
      certas: [
        'Conectar todas as peças e permitir que elas se comuniquem',
        'Ligar as peças entre si, como um sistema nervoso',
      ],
      erradas: [
        'Fazer os cálculos dos programas',
        'Guardar os arquivos quando o PC está desligado',
        'Converter a energia da tomada',
        'Mostrar as imagens na tela',
        'Resfriar o processador',
      ],
      porque: 'A placa-mãe é a "base" que liga processador, memória, armazenamento, placa de vídeo e fonte.',
    }),
    pares({
      d: 3,
      pesquise: 'Pesquise os nomes dos encaixes (slots, soquete e conectores) de uma placa-mãe.',
      pergunta: 'Ligue cada encaixe da placa-mãe à peça que se conecta nele.',
      lista: [
        ['Soquete', 'Processador'],
        ['Slot DIMM', 'Memória RAM'],
        ['Slot PCI Express x16', 'Placa de vídeo'],
        ['Conector SATA', 'HD ou SSD SATA'],
        ['Conector de 24 pinos', 'Cabo da fonte'],
        ['Slot M.2', 'SSD NVMe'],
      ],
      quantidade: 4,
      porque: 'Cada peça tem seu encaixe próprio. Saber os nomes ajuda a conferir se as peças são compatíveis.',
    }),
    vf({
      d: 4,
      pesquise: 'Pesquise o que é o soquete da placa-mãe e se ele é igual em todas as placas.',
      afirmacoes: [
        ['Placas-mãe para processadores Intel e AMD usam soquetes diferentes.', true],
        ['Uma placa-mãe AM4 aceita processadores AMD feitos para AM4, mas não processadores Intel.', true],
        ['Qualquer processador encaixa em qualquer placa-mãe, desde que seja da mesma marca.', false],
        ['O soquete da placa-mãe é o encaixe da memória RAM.', false],
      ],
      porque: 'O soquete é o encaixe do processador. Ele muda entre marcas e gerações, então é preciso conferir a compatibilidade.',
    }),
    ordem({
      d: 5,
      pesquise: 'Pesquise os formatos de placa-mãe E-ATX, ATX, Micro-ATX e Mini-ITX.',
      pergunta: 'Coloque os formatos de placa-mãe do MAIOR para o MENOR.',
      itens: ['E-ATX', 'ATX', 'Micro-ATX', 'Mini-ITX'],
      inicio: 'Maior',
      fim: 'Menor',
      porque: 'E-ATX > ATX > Micro-ATX > Mini-ITX. O gabinete precisa aceitar o formato da placa-mãe escolhida.',
    }),
  ],

  'Processador (CPU)': [
    escrita({
      d: 1,
      pesquise: 'Pesquise qual apelido o processador costuma receber.',
      pergunta: 'O processador é conhecido como o ______ do computador. Qual palavra completa a frase?',
      aceitas: ['cérebro'],
      dica: 'Uma palavra',
      porque: 'O processador é chamado de "cérebro" porque executa as instruções de todos os programas.',
    }),
    vf({
      d: 2,
      pesquise: 'Pesquise o que o processador faz e o que significa a sigla CPU.',
      afirmacoes: [
        ['O processador executa as instruções dos programas.', true],
        ['CPU é a sigla de Central Processing Unit (Unidade Central de Processamento).', true],
        ['O processador guarda suas fotos e jogos mesmo com o computador desligado.', false],
        ['"CPU" é o nome correto do gabinete inteiro do computador.', false],
      ],
      porque: 'A CPU é só o processador (um chip). Muita gente chama o gabinete de "CPU", mas isso não está certo.',
    }),
    slider({
      d: 3,
      pesquise: 'Pesquise o que significam os nomes dual-core, quad-core, hexa-core e octa-core.',
      min: 1,
      max: 16,
      passo: 1,
      unidade: 'núcleos',
      resposta: 4,
      variantes: [
        { pergunta: 'Quantos núcleos tem um processador quad-core?', resposta: 4 },
        { pergunta: 'Quantos núcleos tem um processador dual-core?', resposta: 2 },
        { pergunta: 'Quantos núcleos tem um processador hexa-core?', resposta: 6 },
        { pergunta: 'Quantos núcleos tem um processador octa-core?', resposta: 8 },
      ],
      porque: 'Dual = 2, quad = 4, hexa = 6, octa = 8. Mais núcleos permitem fazer mais tarefas ao mesmo tempo.',
    }),
    mc({
      d: 4,
      pesquise: 'Pesquise o que a frequência de um processador, medida em GHz (gigahertz), indica.',
      pergunta: 'O que o valor em GHz de um processador (ex: 4,2 GHz) indica?',
      certas: ['Quantos ciclos de processamento ele faz por segundo (velocidade do clock)'],
      erradas: [
        'Quanta memória RAM ele tem',
        'Quanta energia ele gasta por hora',
        'A temperatura máxima que ele aguenta',
        'Quantos núcleos ele possui',
      ],
      porque: '1 GHz = 1 bilhão de ciclos por segundo. Mas só GHz não diz tudo: núcleos e geração também contam.',
    }),
    mc({
      d: 5,
      pesquise: 'Pesquise o que é vídeo integrado (iGPU) e como saber se um processador tem.',
      pergunta: 'Um PC foi montado SEM placa de vídeo e com um processador SEM vídeo integrado. O que acontece?',
      certas: ['O computador não consegue mostrar imagem no monitor'],
      erradas: [
        'Funciona normal, porque a placa-mãe gera a imagem sozinha',
        'A imagem aparece, só que em preto e branco',
        'O processador vira placa de vídeo automaticamente',
        'O monitor passa a processar a imagem',
      ],
      porque: 'Sem iGPU e sem placa de vídeo, nada gera a imagem. Por isso é importante conferir antes de comprar.',
    }),
  ],

  Cooler: [
    mc({
      d: 1,
      pesquise: 'Pesquise para que serve o cooler do computador.',
      pergunta: 'Qual é a função do cooler?',
      certas: ['Tirar o calor do processador para ele não superaquecer', 'Resfriar o processador'],
      erradas: [
        'Deixar o processador mais rápido',
        'Guardar energia para quando faltar luz',
        'Limpar a poeira do gabinete',
        'Aumentar a memória do computador',
      ],
      porque: 'O processador esquenta muito trabalhando. O cooler leva esse calor embora.',
    }),
    anagrama({
      d: 2,
      pesquise: 'Pesquise como se chama a peça de metal com "aletas" que fica em cima do processador, junto da ventoinha.',
      pergunta: 'Monte o nome dessa peça de metal.',
      palavra: 'DISSIPADOR',
      porque: 'O dissipador espalha o calor pelas aletas, e a ventoinha sopra ar para levá-lo embora.',
    }),
    vf({
      d: 3,
      pesquise: 'Pesquise o que é pasta térmica e onde ela é colocada.',
      afirmacoes: [
        ['A pasta térmica ajuda a passar o calor do processador para o dissipador.', true],
        ['Sem pasta térmica, o processador pode esquentar mais do que deveria.', true],
        ['A pasta térmica serve para colar o processador na placa-mãe.', false],
        ['A pasta térmica é usada para deixar a placa de vídeo mais rápida.', false],
      ],
      porque: 'A pasta preenche os micro-espaços entre o processador e o dissipador, melhorando a troca de calor.',
    }),
    ordem({
      d: 4,
      pesquise: 'Pesquise o caminho que o calor faz desde o processador até sair do gabinete.',
      pergunta: 'Coloque em ordem o caminho do calor.',
      itens: ['Processador', 'Pasta térmica', 'Dissipador', 'Ventoinha', 'Ar para fora do gabinete'],
      inicio: 'Começa',
      fim: 'Termina',
      porque: 'O calor passa do chip para a pasta, depois para o dissipador, e a ventoinha empurra o ar quente para fora.',
    }),
    mc({
      d: 5,
      pesquise: 'Pesquise o que significa "thermal throttling".',
      pergunta: 'Quando o processador fica quente demais, o que ele costuma fazer para se proteger?',
      certas: ['Diminui a própria velocidade (thermal throttling)'],
      erradas: [
        'Aumenta a velocidade para terminar logo',
        'Apaga os arquivos do HD',
        'Liga a placa de vídeo no lugar dele',
        'Passa a usar a memória RAM para esfriar',
      ],
      porque: 'Com o thermal throttling o processador reduz o desempenho para baixar a temperatura. Cooler ruim = PC lento.',
    }),
  ],

  'Memória RAM': [
    vf({
      d: 1,
      pesquise: 'Pesquise o que acontece com o conteúdo da memória RAM quando o computador desliga.',
      afirmacoes: [
        ['Quando o computador desliga, o que está na memória RAM é apagado.', true],
        ['A RAM é uma memória temporária, usada enquanto os programas estão abertos.', true],
        ['A memória RAM guarda seus arquivos para sempre, mesmo sem energia.', false],
        ['Salvar um documento significa guardar ele na memória RAM.', false],
      ],
      porque: 'A RAM é volátil: sem energia ela perde tudo. Arquivos salvos ficam no HD/SSD.',
    }),
    escrita({
      d: 2,
      pesquise: 'Pesquise o que significa a sigla RAM em inglês.',
      pergunta: 'RAM significa Random Access ______. Qual palavra (em inglês) está faltando?',
      aceitas: ['memory'],
      dica: 'Uma palavra em inglês',
      porque: 'Random Access Memory = Memória de Acesso Aleatório.',
    }),
    slider({
      d: 3,
      pesquise: 'Pesquise quantos megabytes (MB) existem em 1 gigabyte (GB) na conta do computador (base 2).',
      min: 0,
      max: 10240,
      passo: 512,
      unidade: 'MB',
      resposta: 4096,
      variantes: [
        { pergunta: 'Um pente de memória de 2 GB tem quantos MB? (1 GB = 1024 MB)', resposta: 2048 },
        { pergunta: 'Um pente de memória de 4 GB tem quantos MB? (1 GB = 1024 MB)', resposta: 4096 },
        { pergunta: 'Um pente de memória de 8 GB tem quantos MB? (1 GB = 1024 MB)', resposta: 8192 },
      ],
      porque: 'Na base 2, cada GB tem 1024 MB. Então é só multiplicar os GB por 1024.',
    }),
    mc({
      d: 4,
      pesquise: 'Pesquise a diferença entre memória DDR4 e DDR5 e se uma pode ser usada no lugar da outra.',
      pergunta: 'Uma placa-mãe aceita só memória DDR5. O que acontece se tentar usar um pente DDR4?',
      certas: ['Não encaixa: o entalhe (chanfro) do pente fica em outra posição'],
      erradas: [
        'Funciona normal, só fica mais lento',
        'Funciona e fica ainda mais rápido',
        'Funciona se colocar dois pentes',
        'A placa converte DDR4 em DDR5 sozinha',
      ],
      porque: 'Cada geração de memória tem um entalhe em lugar diferente justamente para impedir o encaixe errado.',
    }),
    vf({
      d: 5,
      pesquise: 'Pesquise o que é "dual channel" e por que se recomenda usar 2 pentes iguais.',
      afirmacoes: [
        ['Dois pentes de 8 GB em dual channel costumam render mais do que um único pente de 16 GB.', true],
        ['Para usar dual channel, os pentes devem ir nos slots indicados no manual da placa-mãe.', true],
        ['Em dual channel, a memória RAM passa a guardar os arquivos mesmo desligada.', false],
        ['Dual channel significa usar uma memória DDR4 junto com uma DDR5.', false],
      ],
      porque: 'No dual channel o processador acessa dois pentes ao mesmo tempo, o que aumenta a velocidade de comunicação.',
    }),
  ],

  'Armazenamento (HD/SSD)': [
    mc({
      d: 1,
      pesquise: 'Pesquise a diferença entre HD e SSD.',
      pergunta: 'Qual tipo de armazenamento NÃO tem partes que giram e costuma ser muito mais rápido?',
      certas: ['SSD'],
      erradas: ['HD', 'Disquete', 'CD-ROM'],
      porque: 'O HD tem discos girando; o SSD usa chips de memória flash, sem partes móveis.',
    }),
    ordem({
      d: 2,
      pesquise: 'Pesquise as unidades de medida de armazenamento: byte, KB, MB, GB e TB.',
      pergunta: 'Coloque as unidades da MENOR para a MAIOR.',
      itens: ['Byte', 'Kilobyte (KB)', 'Megabyte (MB)', 'Gigabyte (GB)', 'Terabyte (TB)'],
      inicio: 'Menor',
      fim: 'Maior',
      porque: 'Cada unidade é cerca de mil vezes a anterior (1024 vezes na conta do computador).',
    }),
    slider({
      d: 3,
      pesquise: 'Pesquise quantos MB existem em 1 GB (1 GB = 1024 MB) e faça a divisão.',
      min: 0,
      max: 600,
      passo: 1,
      unidade: 'fotos',
      resposta: 256,
      variantes: [
        { pergunta: 'Cada foto tem 4 MB. Quantas fotos cabem em exatamente 1 GB?', resposta: 256 },
        { pergunta: 'Cada foto tem 2 MB. Quantas fotos cabem em exatamente 1 GB?', resposta: 512 },
        { pergunta: 'Cada foto tem 8 MB. Quantas fotos cabem em exatamente 1 GB?', resposta: 128 },
      ],
      porque: '1 GB = 1024 MB. Divida 1024 pelo tamanho de cada foto.',
    }),
    pares({
      d: 4,
      pesquise: 'Pesquise os tipos de armazenamento: HD, SSD SATA, SSD NVMe (M.2) e pen drive.',
      pergunta: 'Ligue cada tipo de armazenamento à sua característica.',
      lista: [
        ['HD', 'Tem discos magnéticos que giram'],
        ['SSD SATA', 'Sem partes móveis, usa o mesmo cabo de dados do HD'],
        ['SSD NVMe (M.2)', 'Encaixa direto na placa-mãe e é o mais rápido'],
        ['Pen drive', 'Memória flash portátil ligada na porta USB'],
      ],
      porque: 'Do mais lento ao mais rápido: HD < SSD SATA < SSD NVMe.',
    }),
    vf({
      d: 5,
      pesquise: 'Pesquise por que um HD "de 1 TB" aparece com cerca de 931 GB no computador.',
      afirmacoes: [
        ['Um HD vendido como 1 TB aparece com cerca de 931 GB porque o fabricante conta em base 10 e o sistema em base 2.', true],
        ['Um SSD NVMe costuma ser mais rápido que um SSD SATA.', true],
        ['Um HD de 1 TB aparece com 931 GB porque veio com defeito de fábrica.', false],
        ['É preciso desfragmentar o SSD toda semana para ele não ficar lento.', false],
      ],
      porque: 'Fabricante: 1 TB = 1.000.000.000.000 bytes. Sistema: divide por 1024 três vezes ≈ 931 GB.',
    }),
  ],

  'Placa de vídeo (GPU)': [
    mc({
      d: 1,
      pesquise: 'Pesquise para que serve a placa de vídeo.',
      pergunta: 'Qual é a principal função da placa de vídeo?',
      certas: ['Processar as imagens e gráficos que aparecem na tela'],
      erradas: [
        'Conectar o computador à internet',
        'Guardar arquivos',
        'Resfriar o processador',
        'Ligar o teclado e o mouse',
      ],
      porque: 'A GPU é especialista em gráficos: jogos, vídeos, edição e até inteligência artificial.',
    }),
    escrita({
      d: 2,
      pesquise: 'Pesquise o que significa a sigla GPU.',
      pergunta: 'GPU significa Graphics Processing Unit. Em português: Unidade de Processamento ______. Complete.',
      aceitas: ['gráfico', 'gráfica', 'de gráficos'],
      dica: 'Uma palavra',
      porque: 'GPU = Unidade de Processamento Gráfico.',
    }),
    vf({
      d: 3,
      pesquise: 'Pesquise o que é VRAM (memória de vídeo) e onde ela fica.',
      afirmacoes: [
        ['A VRAM é a memória que fica na própria placa de vídeo.', true],
        ['Jogos com gráficos mais pesados costumam precisar de mais VRAM.', true],
        ['A VRAM é o mesmo que a memória RAM comum do computador.', false],
        ['A VRAM guarda as fotos do computador quando ele desliga.', false],
      ],
      porque: 'A VRAM guarda texturas e imagens que a GPU está usando naquele momento.',
    }),
    slider({
      d: 4,
      pesquise: 'Pesquise o que é FPS (quadros por segundo).',
      min: 0,
      max: 600,
      passo: 1,
      unidade: 'quadros',
      resposta: 300,
      variantes: [
        { pergunta: 'Um jogo roda a 60 FPS. Quantos quadros aparecem em 5 segundos?', resposta: 300 },
        { pergunta: 'Um jogo roda a 144 FPS. Quantos quadros aparecem em 2 segundos?', resposta: 288 },
        { pergunta: 'Um jogo roda a 30 FPS. Quantos quadros aparecem em 12 segundos?', resposta: 360 },
        { pergunta: 'Um jogo roda a 120 FPS. Quantos quadros aparecem em 4 segundos?', resposta: 480 },
      ],
      porque: 'FPS é quantos quadros por segundo. Multiplique o FPS pelos segundos.',
    }),
    mc({
      d: 5,
      pesquise: 'Pesquise onde se liga o cabo do monitor quando o PC tem placa de vídeo dedicada.',
      pergunta: 'Num PC com placa de vídeo dedicada, onde o cabo do monitor deve ser ligado para usar a potência dela?',
      certas: ['Nas saídas de vídeo da própria placa de vídeo'],
      erradas: [
        'Nas saídas de vídeo da placa-mãe',
        'Em uma porta USB',
        'Na fonte de alimentação',
        'Em qualquer lugar, dá no mesmo',
      ],
      porque: 'Ligando na placa-mãe, quem gera a imagem é o vídeo integrado (se existir), e não a placa dedicada.',
    }),
  ],

  Monitor: [
    vf({
      d: 1,
      pesquise: 'Pesquise se o monitor é um dispositivo de entrada ou de saída.',
      afirmacoes: [
        ['O monitor é um dispositivo de saída: ele mostra informações do computador.', true],
        ['Um monitor comum não executa os programas — quem faz isso é o computador.', true],
        ['O monitor é um dispositivo de entrada: ele envia informações para o computador.', false],
        ['O monitor guarda os arquivos que aparecem na tela.', false],
      ],
      porque: 'Entrada manda dados PARA o computador (teclado). Saída mostra dados DO computador (monitor).',
    }),
    pares({
      d: 2,
      pesquise: 'Pesquise o que significam polegadas, resolução e taxa de atualização (Hz) num monitor.',
      pergunta: 'Ligue cada termo ao seu significado.',
      lista: [
        ['Polegadas', 'Tamanho da diagonal da tela'],
        ['Hz (hertz)', 'Quantas vezes a imagem atualiza por segundo'],
        ['Resolução', 'Quantidade de pixels na tela'],
        ['HDMI', 'Cabo que leva imagem e som digital'],
      ],
      porque: 'Esses termos aparecem em todo anúncio de monitor — entender cada um ajuda a escolher bem.',
    }),
    slider({
      d: 3,
      pesquise: 'Pesquise as resoluções HD (1280 x 720), Full HD (1920 x 1080) e 4K (3840 x 2160).',
      min: 0,
      max: 4000,
      passo: 40,
      unidade: 'pixels',
      resposta: 1080,
      variantes: [
        { pergunta: 'Um monitor Full HD tem 1920 pixels de largura. Quantos pixels ele tem de altura?', resposta: 1080 },
        { pergunta: 'Um monitor 4K (UHD) tem 2160 pixels de altura. Quantos pixels ele tem de largura?', resposta: 3840 },
        { pergunta: 'Uma tela HD tem 1280 pixels de largura. Quantos pixels ela tem de altura?', resposta: 720 },
      ],
      porque: 'A resolução é largura x altura em pixels: HD 1280x720, Full HD 1920x1080, 4K 3840x2160.',
    }),
    mc({
      d: 4,
      pesquise: 'Pesquise o que é taxa de atualização (Hz) e por que monitores gamer têm 144 Hz ou mais.',
      pergunta: 'Comparado a um monitor de 60 Hz, um monitor de 144 Hz…',
      certas: ['atualiza a imagem mais vezes por segundo, deixando o movimento mais suave'],
      erradas: ['tem a tela maior', 'mostra mais cores', 'sempre gasta menos energia', 'deixa a internet mais rápida'],
      porque: '144 Hz = a tela desenha a imagem 144 vezes por segundo, contra 60 vezes no monitor de 60 Hz.',
    }),
    vf({
      d: 5,
      pesquise: 'Pesquise o que é pixel e o que acontece com a nitidez quando a mesma resolução é usada numa tela maior.',
      afirmacoes: [
        ['Em uma tela de 27", a resolução Full HD fica menos nítida do que numa tela de 21", porque os pixels ficam maiores.', true],
        ['Pixel é o menor ponto de imagem de uma tela.', true],
        ['Quanto maior a tela, mais pixels ela tem, qualquer que seja a resolução.', false],
        ['Um monitor de 60 Hz consegue mostrar 144 imagens diferentes por segundo.', false],
      ],
      porque: 'A mesma quantidade de pixels espalhada numa tela maior deixa cada pixel maior e a imagem menos nítida.',
    }),
  ],

  'Fonte de Alimentação': [
    mc({
      d: 1,
      pesquise: 'Pesquise qual é a função da fonte de alimentação do computador.',
      pergunta: 'O que a fonte de alimentação faz?',
      certas: ['Converte a energia da tomada para as peças do computador poderem usar'],
      erradas: [
        'Guarda energia como uma bateria para quando faltar luz',
        'Deixa a internet mais rápida',
        'Resfria a placa de vídeo',
        'Guarda os arquivos do computador',
      ],
      porque: 'A tomada fornece corrente alternada (127 V/220 V); a fonte transforma em tensões menores (12 V, 5 V, 3,3 V).',
    }),
    anagrama({
      d: 2,
      pesquise: 'Pesquise em qual unidade de medida se informa a potência de uma fonte (ex: 500 ___).',
      pergunta: 'Monte o nome da unidade de potência elétrica.',
      palavra: 'WATTS',
      porque: 'A potência é medida em watts (W). Uma fonte de 500 W fornece até 500 watts.',
    }),
    vf({
      d: 3,
      pesquise: 'Pesquise o que é um nobreak e se a fonte do computador de mesa tem bateria.',
      afirmacoes: [
        ['A fonte de um computador de mesa não tem bateria: se a luz acabar, o PC desliga.', true],
        ['O nobreak é um aparelho que mantém o computador ligado por alguns minutos quando falta energia.', true],
        ['A fonte funciona como bateria e mantém o PC ligado por horas sem luz.', false],
        ['Uma fonte mais potente deixa o processador mais rápido.', false],
      ],
      porque: 'Quem segura o PC ligado sem energia é o nobreak. A fonte só converte energia.',
    }),
    slider({
      d: 4,
      pesquise: 'Pesquise como calcular o consumo de um PC somando os watts das peças.',
      min: 0,
      max: 600,
      passo: 5,
      unidade: 'W',
      resposta: 335,
      variantes: [
        { pergunta: 'Processador de 65 W, placa de vídeo de 170 W e o resto das peças gasta 100 W. Quanto o PC consome no total?', resposta: 335 },
        { pergunta: 'Processador de 105 W, placa de vídeo de 220 W e o resto das peças gasta 90 W. Quanto o PC consome no total?', resposta: 415 },
        { pergunta: 'Processador de 65 W, sem placa de vídeo, e o resto das peças gasta 80 W. Quanto o PC consome no total?', resposta: 145 },
      ],
      porque: 'Some o consumo de todas as peças. Depois escolha uma fonte com folga (uns 30% a mais) e de boa qualidade.',
    }),
    mc({
      d: 5,
      pesquise: 'Pesquise o que significa o selo "80 Plus" nas fontes.',
      pergunta: 'O que o selo 80 Plus indica em uma fonte?',
      certas: ['Que ela aproveita pelo menos 80% da energia, desperdiçando menos em calor'],
      erradas: [
        'Que ela tem 80 watts de potência',
        'Que ela dura pelo menos 80 anos',
        'Que ela só funciona em 80 volts',
        'Que ela tem 80 cabos de energia',
      ],
      porque: 'Fontes 80 Plus (Bronze, Gold, Platinum...) são mais eficientes: gastam menos luz e esquentam menos.',
    }),
  ],

  Gabinete: [
    vf({
      d: 1,
      pesquise: 'Pesquise qual é a função do gabinete.',
      afirmacoes: [
        ['O gabinete é a "caixa" que protege e organiza as peças do computador.', true],
        ['O gabinete ajuda a organizar a circulação de ar dentro do PC.', true],
        ['O gabinete é o que processa os programas do computador.', false],
        ['Trocar o gabinete aumenta a memória RAM do computador.', false],
      ],
      porque: 'O gabinete protege, organiza e ventila as peças — mas quem processa é o processador.',
    }),
    mc({
      d: 2,
      pesquise: 'Pesquise para que servem as ventoinhas (fans) extras de um gabinete.',
      pergunta: 'Para que servem as ventoinhas extras do gabinete?',
      certas: ['Fazer o ar circular: entra ar frio e sai ar quente'],
      erradas: [
        'Deixar a internet mais rápida',
        'Gerar energia para as peças',
        'Guardar arquivos extras',
        'Remover vírus do computador',
      ],
      porque: 'Um bom fluxo de ar mantém as peças frias e evita perda de desempenho.',
    }),
    ordem({
      d: 3,
      pesquise: 'Pesquise os tamanhos de gabinete: compacto (Mini-ITX), Mini Tower, Mid Tower e Full Tower.',
      pergunta: 'Coloque os gabinetes do MENOR para o MAIOR.',
      itens: ['Compacto (Mini-ITX)', 'Mini Tower', 'Mid Tower', 'Full Tower'],
      inicio: 'Menor',
      fim: 'Maior',
      porque: 'Quanto maior o gabinete, maiores as placas-mãe e mais peças e ventoinhas ele comporta.',
    }),
    mc({
      d: 4,
      pesquise: 'Pesquise quais tamanhos de placa-mãe cabem em cada tipo de gabinete.',
      variantes: [
        {
          pergunta: 'Um gabinete Mini Tower aceita placas de até Micro-ATX. Qual destas placas NÃO cabe nele?',
          corretas: ['ATX'],
          incorretas: ['Micro-ATX', 'Mini-ITX'],
        },
        {
          pergunta: 'Um gabinete compacto aceita só placas Mini-ITX. Qual placa cabe nele?',
          corretas: ['Mini-ITX'],
          incorretas: ['ATX', 'Micro-ATX', 'E-ATX'],
        },
      ],
      certas: ['ATX'],
      erradas: ['Micro-ATX', 'Mini-ITX'],
      porque: 'Gabinetes maiores aceitam placas menores, mas o contrário não: uma placa ATX não cabe num Mini Tower.',
    }),
    vf({
      d: 5,
      pesquise: 'Pesquise o que é fluxo de ar (airflow) e onde costumam ficar as ventoinhas de entrada e de saída.',
      afirmacoes: [
        ['Normalmente o ar frio entra pela frente do gabinete e o ar quente sai por trás e por cima.', true],
        ['Como o ar quente sobe, ventoinhas no topo costumam ser de saída.', true],
        ['O ideal é que todas as ventoinhas soprem ar para dentro, sem nenhuma saída.', false],
        ['Um gabinete totalmente fechado, sem ventilação, deixa as peças mais frias.', false],
      ],
      porque: 'Um caminho de ar bem definido (frente → trás/topo) tira o calor de dentro do gabinete.',
    }),
  ],

  Teclado: [
    mc({
      d: 1,
      pesquise: 'Pesquise se o teclado é um dispositivo de entrada ou de saída.',
      pergunta: 'O teclado é um dispositivo de…',
      certas: ['Entrada: envia informações para o computador'],
      erradas: ['Saída: mostra informações', 'Armazenamento: guarda arquivos', 'Processamento: executa programas'],
      porque: 'Tudo que você digita vai do teclado para o computador — por isso ele é de entrada.',
    }),
    anagrama({
      d: 2,
      pesquise: 'Pesquise o nome do layout de teclado mais usado no mundo, formado pelas primeiras letras da fileira de cima.',
      pergunta: 'Monte o nome desse layout de teclado.',
      palavra: 'QWERTY',
      porque: 'Q-W-E-R-T-Y são as 6 primeiras letras da fileira de cima do teclado.',
    }),
    escrita({
      d: 3,
      pesquise: 'Pesquise o nome do padrão de teclado brasileiro, que tem a tecla Ç.',
      pergunta: 'Qual é o nome do padrão de teclado brasileiro que tem a tecla Ç?',
      aceitas: ['ABNT2', 'ABNT 2', 'ABNT'],
      dica: 'Uma sigla (com número)',
      porque: 'O ABNT2 é o padrão brasileiro: tem Ç, acentos e a tecla / perto do Shift direito.',
    }),
    pares({
      d: 4,
      pesquise: 'Pesquise os atalhos de teclado mais usados no computador.',
      pergunta: 'Ligue cada atalho à sua função.',
      lista: [
        ['Ctrl + C', 'Copiar'],
        ['Ctrl + V', 'Colar'],
        ['Ctrl + Z', 'Desfazer'],
        ['Ctrl + X', 'Recortar'],
        ['Ctrl + S', 'Salvar'],
        ['Alt + Tab', 'Trocar de janela'],
      ],
      quantidade: 4,
      porque: 'Atalhos economizam tempo — Ctrl+C / Ctrl+V / Ctrl+Z funcionam em quase todo programa.',
    }),
    vf({
      d: 5,
      pesquise: 'Pesquise a diferença entre teclado mecânico e teclado de membrana.',
      afirmacoes: [
        ['O teclado mecânico tem uma chave (switch) individual embaixo de cada tecla.', true],
        ['O teclado de membrana usa uma camada flexível que fecha o contato quando a tecla é apertada.', true],
        ['Teclado mecânico é o nome dado a qualquer teclado sem fio.', false],
        ['Todo teclado de membrana tem um switch mecânico em cada tecla.', false],
      ],
      porque: 'Mecânico = um switch por tecla (mais durável e preciso). Membrana = uma manta única, mais simples e barata.',
    }),
  ],

  Mouse: [
    vf({
      d: 1,
      pesquise: 'Pesquise se o mouse é um dispositivo de entrada ou de saída e como o mouse óptico funciona.',
      afirmacoes: [
        ['O mouse é um dispositivo de entrada.', true],
        ['O mouse óptico usa luz e um sensor para perceber o movimento.', true],
        ['O mouse é um dispositivo de saída, porque mostra a seta na tela.', false],
        ['Todo mouse precisa de uma bolinha embaixo para funcionar.', false],
      ],
      porque: 'O mouse envia movimentos e cliques para o computador. Quem desenha a seta é a placa de vídeo.',
    }),
    mc({
      d: 2,
      pesquise: 'Pesquise por que esse aparelho recebeu o nome "mouse" (rato, em inglês).',
      pergunta: 'Por que ele se chama "mouse"?',
      certas: ['Porque o formato e o fio lembravam um rato com rabo'],
      erradas: [
        'Porque foi inventado por alguém com o sobrenome Mouse',
        'Porque faz barulho de rato',
        'Porque foi criado para caçar vírus',
        'Porque o primeiro era coberto de pelo',
      ],
      porque: 'O corpo pequeno com um fio saindo parecia um ratinho — e o apelido pegou.',
    }),
    escrita({
      d: 3,
      pesquise: 'Pesquise quem inventou o mouse de computador, na década de 1960.',
      pergunta: 'Qual é o sobrenome do inventor do mouse? (Douglas ______)',
      aceitas: ['Engelbart'],
      dica: 'Só o sobrenome',
      porque: 'Douglas Engelbart criou o mouse nos anos 1960. O primeiro protótipo era uma caixinha de madeira!',
    }),
    mc({
      d: 4,
      pesquise: 'Pesquise o que significa DPI num mouse.',
      pergunta: 'O que acontece quando você aumenta o DPI do mouse?',
      certas: ['A seta anda mais na tela com o mesmo movimento da mão'],
      erradas: [
        'O mouse fica mais pesado',
        'A bateria passa a durar mais',
        'O clique fica mais silencioso',
        'A tela ganha mais pixels',
      ],
      porque: 'DPI = pontos por polegada. Mais DPI = mais sensibilidade: a seta percorre mais espaço.',
    }),
    ordem({
      d: 5,
      pesquise: 'Pesquise o caminho de um clique: do dedo até a imagem mudar na tela.',
      pergunta: 'Coloque em ordem o que acontece num clique.',
      itens: [
        'Você aperta o botão do mouse',
        'O mouse envia o sinal para o computador',
        'O processador interpreta o clique',
        'A placa de vídeo desenha o resultado',
        'A imagem atualizada aparece no monitor',
      ],
      inicio: 'Começa',
      fim: 'Termina',
      porque: 'Entrada (mouse) → processamento (CPU) → saída (GPU e monitor). É o ciclo de todo computador.',
    }),
  ],

  // ========================== NÍVEL 2 — PERIFÉRICOS ==========================

  'Porta USB': [
    escrita({
      d: 1,
      pesquise: 'Pesquise o que significa a sigla USB.',
      pergunta: 'USB é a sigla de Universal Serial ______. Qual palavra (em inglês) falta?',
      aceitas: ['bus'],
      dica: 'Uma palavra em inglês, 3 letras',
      porque: 'USB = Universal Serial Bus (Barramento Serial Universal).',
    }),
    vf({
      d: 2,
      pesquise: 'Pesquise o que pode ser ligado na porta USB e os tipos de conector (USB-A e USB-C).',
      afirmacoes: [
        ['Pela porta USB dá para conectar teclado, mouse, pen drive e impressora.', true],
        ['O conector USB-C pode ser encaixado de qualquer lado.', true],
        ['A porta USB só serve para carregar celular.', false],
        ['O conector USB-A (o retangular comum) encaixa dos dois lados.', false],
      ],
      porque: 'O USB é "universal": liga quase todo tipo de periférico. O USB-C é reversível; o USB-A não.',
    }),
    ordem({
      d: 3,
      pesquise: 'Pesquise as versões do USB: 1.1, 2.0, 3.0 e USB4.',
      pergunta: 'Ordene as versões do USB da MAIS LENTA para a MAIS RÁPIDA.',
      itens: ['USB 1.1', 'USB 2.0', 'USB 3.0', 'USB4'],
      inicio: 'Mais lenta',
      fim: 'Mais rápida',
      porque: 'Cada nova versão aumentou bastante a velocidade de transferência.',
    }),
    mc({
      d: 4,
      pesquise: 'Pesquise como identificar pela cor uma porta USB 3.0 no computador.',
      pergunta: 'Qual cor costuma indicar uma porta USB 3.0?',
      certas: ['Azul'],
      erradas: ['Preta', 'Branca', 'Amarela'],
      porque: 'Por padrão: branca = USB 1.x, preta = USB 2.0, azul = USB 3.0. Amarela costuma ser porta que carrega mesmo com PC desligado.',
    }),
    pares({
      d: 5,
      pesquise: 'Pesquise a velocidade máxima de cada versão do USB.',
      pergunta: 'Ligue cada versão do USB à sua velocidade máxima.',
      lista: [
        ['USB 1.1', '12 Mbps'],
        ['USB 2.0', '480 Mbps'],
        ['USB 3.0 (3.2 Gen 1)', '5 Gbps'],
        ['USB 3.2 Gen 2', '10 Gbps'],
        ['USB4', '40 Gbps'],
      ],
      quantidade: 4,
      porque: 'Mbps = milhões de bits por segundo; Gbps = bilhões. Um USB 3.0 é umas 10 vezes mais rápido que o 2.0.',
    }),
  ],

  'Pen Drive': [
    mc({
      d: 1,
      pesquise: 'Pesquise para que serve um pen drive.',
      pergunta: 'Para que serve um pen drive?',
      certas: ['Guardar e levar arquivos de um computador para outro'],
      erradas: [
        'Aumentar a velocidade do processador',
        'Conectar o computador à internet',
        'Resfriar as peças',
        'Imprimir documentos',
      ],
      porque: 'O pen drive é um armazenamento portátil: você grava num PC e abre em outro.',
    }),
    vf({
      d: 2,
      pesquise: 'Pesquise se o pen drive perde os arquivos quando é desconectado e o que é "remover com segurança".',
      afirmacoes: [
        ['Os arquivos continuam no pen drive depois que ele é desconectado.', true],
        ['É recomendado usar "Ejetar" ou "Remover com segurança" antes de tirar o pen drive.', true],
        ['O pen drive apaga tudo quando é tirado do computador.', false],
        ['O pen drive precisa de pilha para guardar os arquivos.', false],
      ],
      porque: 'A memória flash guarda os dados sem energia. Ejetar antes evita corromper um arquivo sendo gravado.',
    }),
    anagrama({
      d: 3,
      pesquise: 'Pesquise o nome do tipo de memória usada nos pen drives e SSDs, que não tem partes móveis.',
      pergunta: 'Monte o nome desse tipo de memória (memória ______).',
      palavra: 'FLASH',
      porque: 'A memória flash guarda os dados em chips, sem precisar de energia e sem partes móveis.',
    }),
    slider({
      d: 4,
      pesquise: 'Pesquise quantos MB cabem em 1 GB (1 GB = 1024 MB) e faça a conta.',
      min: 0,
      max: 64,
      passo: 1,
      unidade: 'vídeos',
      resposta: 32,
      variantes: [
        { pergunta: 'Um pen drive de 16 GB vai guardar vídeos de 512 MB cada. Quantos vídeos cabem?', resposta: 32 },
        { pergunta: 'Um pen drive de 4 GB vai guardar vídeos de 256 MB cada. Quantos vídeos cabem?', resposta: 16 },
        { pergunta: 'Um pen drive de 8 GB vai guardar vídeos de 1 GB cada. Quantos vídeos cabem?', resposta: 8 },
        { pergunta: 'Um pen drive de 2 GB vai guardar vídeos de 512 MB cada. Quantos vídeos cabem?', resposta: 4 },
      ],
      porque: 'Transforme GB em MB (x 1024) e divida pelo tamanho de cada vídeo.',
    }),
    mc({
      d: 5,
      pesquise: 'Pesquise os sistemas de arquivos FAT32, exFAT e NTFS e o limite de tamanho de arquivo do FAT32.',
      pergunta: 'Por que não dá para copiar um arquivo de 6 GB para um pen drive formatado em FAT32?',
      certas: ['Porque o FAT32 só aceita arquivos de até 4 GB'],
      erradas: [
        'Porque o pen drive precisa estar vazio',
        'Porque arquivos grandes só podem ir para a nuvem',
        'Porque a porta USB não transfere arquivos grandes',
        'Porque o pen drive esquenta demais',
      ],
      porque: 'No FAT32 cada arquivo pode ter no máximo 4 GB. Formatando em exFAT ou NTFS esse limite some.',
    }),
  ],

  Impressora: [
    vf({
      d: 1,
      pesquise: 'Pesquise se a impressora é dispositivo de entrada ou de saída e como ela pode se conectar.',
      afirmacoes: [
        ['A impressora é um dispositivo de saída: ela coloca no papel o que está no computador.', true],
        ['Existem impressoras que se conectam por Wi-Fi, sem cabo.', true],
        ['A impressora é um dispositivo de entrada.', false],
        ['Toda impressora precisa ficar dentro do gabinete.', false],
      ],
      porque: 'A impressora recebe dados do computador e os coloca no papel — é saída.',
    }),
    pares({
      d: 2,
      pesquise: 'Pesquise os tipos de impressora: jato de tinta, laser, térmica e 3D.',
      pergunta: 'Ligue cada tipo de impressora ao jeito que ela imprime.',
      lista: [
        ['Jato de tinta', 'Solta gotinhas de tinta líquida'],
        ['Laser', 'Usa toner (um pó) e calor'],
        ['Térmica', 'Usa calor em papel especial, como em notinhas de loja'],
        ['3D', 'Cria objetos camada por camada'],
      ],
      porque: 'Cada tecnologia serve para um uso: fotos, documentos em grande quantidade, cupons ou objetos.',
    }),
    escrita({
      d: 3,
      pesquise: 'Pesquise como se chama o pó usado pelas impressoras a laser no lugar da tinta líquida.',
      pergunta: 'Qual é o nome desse pó?',
      aceitas: ['toner'],
      dica: 'Uma palavra',
      porque: 'O toner é um pó que gruda no papel e é fixado com calor.',
    }),
    mc({
      d: 4,
      pesquise: 'Pesquise o que significa DPI em impressoras.',
      pergunta: 'Comparada a uma impressora de 300 DPI, uma de 1200 DPI…',
      certas: ['imprime mais pontos por polegada, com mais detalhes'],
      erradas: [
        'imprime 4 vezes mais páginas por minuto',
        'gasta 4 vezes menos tinta',
        'imprime em folhas maiores',
        'só imprime em preto e branco',
      ],
      porque: 'DPI = dots per inch (pontos por polegada). Mais pontos = imagem mais detalhada.',
    }),
    ordem({
      d: 5,
      pesquise: 'Pesquise o que significa a sigla CMYK nas impressoras coloridas.',
      pergunta: 'CMYK são as 4 tintas das impressoras coloridas. Coloque as cores na mesma ordem das letras C, M, Y, K.',
      itens: ['Ciano', 'Magenta', 'Amarelo (Yellow)', 'Preto (Key)'],
      inicio: 'C',
      fim: 'K',
      porque: 'Misturando ciano, magenta e amarelo (mais o preto) a impressora forma todas as outras cores.',
    }),
  ],

  Scanner: [
    mc({
      d: 1,
      pesquise: 'Pesquise para que serve um scanner.',
      pergunta: 'O que um scanner faz?',
      certas: ['Transforma um documento de papel em arquivo digital'],
      erradas: [
        'Imprime documentos',
        'Guarda arquivos para sempre',
        'Aumenta o volume do som',
        'Conecta o computador ao Wi-Fi',
      ],
      porque: 'O scanner "fotografa" o papel e envia a imagem para o computador.',
    }),
    vf({
      d: 2,
      pesquise: 'Pesquise se o scanner é dispositivo de entrada ou de saída e onde mais ele aparece.',
      afirmacoes: [
        ['O scanner é um dispositivo de entrada.', true],
        ['Muitas impressoras multifuncionais também têm scanner.', true],
        ['O scanner é um dispositivo de saída, porque imprime no papel.', false],
        ['O scanner só consegue digitalizar fotos, nunca textos.', false],
      ],
      porque: 'O scanner manda a imagem PARA o computador: é entrada.',
    }),
    anagrama({
      d: 3,
      pesquise: 'Pesquise o verbo usado para "passar um papel para o computador" com o scanner.',
      pergunta: 'Monte o verbo que significa transformar um papel em arquivo no computador.',
      palavra: 'DIGITALIZAR',
      porque: 'Digitalizar (ou escanear) é transformar algo físico em arquivo digital.',
    }),
    escrita({
      d: 4,
      pesquise: 'Pesquise a sigla da tecnologia que transforma o texto de uma imagem escaneada em texto editável.',
      pergunta: 'Qual é a sigla dessa tecnologia?',
      aceitas: ['OCR'],
      dica: 'Sigla de 3 letras',
      porque: 'OCR = Optical Character Recognition (Reconhecimento Óptico de Caracteres).',
    }),
    mc({
      d: 5,
      pesquise: 'Pesquise o que acontece com o tamanho do arquivo quando se escaneia com mais DPI.',
      pergunta: 'Escanear a mesma folha com 600 DPI em vez de 300 DPI costuma…',
      certas: ['gerar um arquivo maior, com mais detalhes'],
      erradas: [
        'gerar um arquivo menor',
        'deixar o arquivo em preto e branco',
        'não mudar nada no arquivo',
        'apagar o documento original',
      ],
      porque: 'Dobrar o DPI dobra os pontos na largura e na altura: cerca de 4 vezes mais pixels.',
    }),
  ],

  Webcam: [
    vf({
      d: 1,
      pesquise: 'Pesquise se a webcam é dispositivo de entrada ou de saída e para que ela é usada.',
      afirmacoes: [
        ['A webcam é um dispositivo de entrada: ela captura imagem e envia para o computador.', true],
        ['A webcam é usada em videochamadas e aulas online.', true],
        ['A webcam é um dispositivo de saída.', false],
        ['A webcam serve para imprimir fotos.', false],
      ],
      porque: 'A webcam captura vídeo e manda para o computador — é entrada.',
    }),
    mc({
      d: 2,
      pesquise: 'Pesquise em quais situações a webcam é necessária.',
      pergunta: 'Qual destas atividades PRECISA de uma webcam?',
      certas: ['Aparecer em vídeo numa videochamada', 'Gravar um vídeo seu pelo computador'],
      erradas: [
        'Ouvir música',
        'Digitar um trabalho',
        'Imprimir um documento',
        'Salvar arquivos no pen drive',
      ],
      porque: 'Sem câmera não há como capturar sua imagem.',
    }),
    ordem({
      d: 3,
      pesquise: 'Pesquise as resoluções de vídeo 480p, 720p (HD), 1080p (Full HD) e 2160p (4K).',
      pergunta: 'Ordene as resoluções da MENOR para a MAIOR.',
      itens: ['480p', '720p (HD)', '1080p (Full HD)', '2160p (4K)'],
      inicio: 'Menor',
      fim: 'Maior',
      porque: 'O número indica as linhas de pixels na altura: quanto maior, mais nítido.',
    }),
    vf({
      d: 4,
      pesquise: 'Pesquise cuidados de privacidade com a webcam.',
      afirmacoes: [
        ['Uma tampa na webcam ajuda a proteger a privacidade quando ela não está em uso.', true],
        ['A luz acesa ao lado da webcam costuma indicar que ela está ligada.', true],
        ['Permitir que qualquer site use a câmera é sempre seguro.', false],
        ['Programas maliciosos nunca conseguem acessar uma webcam.', false],
      ],
      porque: 'Só permita a câmera em sites confiáveis e cubra a lente quando não estiver usando.',
    }),
    slider({
      d: 5,
      pesquise: 'Pesquise o que é FPS (quadros por segundo) em vídeos.',
      min: 0,
      max: 4000,
      passo: 10,
      unidade: 'quadros',
      resposta: 1800,
      variantes: [
        { pergunta: 'Uma webcam grava a 30 FPS. Quantos quadros ela captura em 1 minuto?', resposta: 1800 },
        { pergunta: 'Uma webcam grava a 60 FPS. Quantos quadros ela captura em 1 minuto?', resposta: 3600 },
        { pergunta: 'Uma webcam grava a 30 FPS. Quantos quadros ela captura em 20 segundos?', resposta: 600 },
        { pergunta: 'Uma webcam grava a 24 FPS. Quantos quadros ela captura em 10 segundos?', resposta: 240 },
      ],
      porque: 'Quadros = FPS x segundos. Lembre que 1 minuto tem 60 segundos.',
    }),
  ],

  Headset: [
    mc({
      d: 1,
      pesquise: 'Pesquise a diferença entre um headset e um fone de ouvido comum.',
      pergunta: 'O que um headset tem que um fone comum normalmente não tem?',
      certas: ['Um microfone'],
      erradas: ['Uma tela', 'Um teclado', 'Uma câmera', 'Um pen drive'],
      porque: 'Headset = fone + microfone, ótimo para chamadas e jogos online.',
    }),
    vf({
      d: 2,
      pesquise: 'Pesquise se o headset é de entrada, de saída ou os dois.',
      afirmacoes: [
        ['O headset é de entrada e saída: o fone é saída e o microfone é entrada.', true],
        ['Um headset Bluetooth funciona sem cabo.', true],
        ['O headset é apenas um dispositivo de saída.', false],
        ['Todo headset precisa de internet para funcionar.', false],
      ],
      porque: 'Dispositivos de entrada e saída fazem as duas coisas — como o headset e a tela touch.',
    }),
    pares({
      d: 3,
      pesquise: 'Pesquise os tipos de conexão de fones e headsets: P2, USB e Bluetooth.',
      pergunta: 'Ligue cada termo à sua descrição.',
      lista: [
        ['P2 (3,5 mm)', 'Plugue redondo de áudio'],
        ['USB', 'Conector que também leva dados e energia'],
        ['Bluetooth', 'Conexão sem fio de curto alcance'],
        ['Microfone', 'Parte que capta a sua voz'],
      ],
      porque: 'P2 é analógico e simples; USB é digital; Bluetooth é sem fio, mas depende de bateria.',
    }),
    mc({
      d: 4,
      pesquise: 'Pesquise o que é latência (atraso) no áudio sem fio.',
      pergunta: 'Por que muitos jogadores preferem headset com fio?',
      certas: ['Porque costuma ter menos atraso (latência) no som'],
      erradas: [
        'Porque o som com fio é sempre mais alto',
        'Porque headset sem fio não tem microfone',
        'Porque headset sem fio não funciona no PC',
        'Porque com fio gasta menos internet',
      ],
      porque: 'Sem fio o áudio precisa ser comprimido e transmitido, o que pode causar um pequeno atraso.',
    }),
    slider({
      d: 5,
      pesquise: 'Pesquise a faixa de frequências que o ouvido humano consegue ouvir, em hertz (Hz).',
      pergunta: 'Uma pessoa jovem ouve sons de cerca de 20 Hz até cerca de quantos hertz?',
      min: 0,
      max: 40000,
      passo: 1000,
      unidade: 'Hz',
      resposta: 20000,
      porque: 'Ouvimos de ~20 Hz a ~20.000 Hz (20 kHz). Com a idade o limite dos agudos diminui.',
    }),
  ],

  'Caixa de Som': [
    vf({
      d: 1,
      pesquise: 'Pesquise se a caixa de som é dispositivo de entrada ou de saída e como ela se conecta.',
      afirmacoes: [
        ['A caixa de som é um dispositivo de saída.', true],
        ['Existem caixas de som que conectam por Bluetooth.', true],
        ['A caixa de som é um dispositivo de entrada, porque capta a voz.', false],
        ['Toda caixa de som precisa de internet para tocar o som do computador.', false],
      ],
      porque: 'A caixa de som reproduz o som que vem do computador — é saída.',
    }),
    mc({
      d: 2,
      pesquise: 'Pesquise o que a potência em watts (W RMS) de uma caixa de som indica.',
      pergunta: 'O que a potência (W RMS) de uma caixa de som indica?',
      certas: ['O quanto de volume ela aguenta sem distorcer o som'],
      erradas: [
        'Quantas músicas ela guarda',
        'A velocidade da internet dela',
        'A cor das luzes dela',
        'O comprimento do cabo',
      ],
      porque: 'RMS é a potência contínua real. Desconfie de números "PMPO" enormes: não medem a mesma coisa.',
    }),
    anagrama({
      d: 3,
      pesquise: 'Pesquise o nome, em inglês, da caixa de som especial para sons graves.',
      pergunta: 'Monte o nome dessa caixa de som.',
      palavra: 'SUBWOOFER',
      porque: 'O subwoofer reproduz os graves (sons de baixa frequência), como a batida da música.',
    }),
    pares({
      d: 4,
      pesquise: 'Pesquise o que significam 2.0, 2.1, 5.1 e 7.1 em sistemas de som.',
      pergunta: 'Ligue cada sistema de som à sua descrição.',
      lista: [
        ['2.0', 'Duas caixas, sem subwoofer'],
        ['2.1', 'Duas caixas + 1 subwoofer'],
        ['5.1', 'Cinco caixas + 1 subwoofer'],
        ['7.1', 'Sete caixas + 1 subwoofer'],
      ],
      porque: 'O primeiro número é a quantidade de caixas; o ".1" é o subwoofer.',
    }),
    mc({
      d: 5,
      pesquise: 'Pesquise o que são decibéis (dB) e a partir de quanto o som pode prejudicar a audição.',
      pergunta: 'O que pode acontecer ao ouvir som muito alto (acima de 85 dB) por muito tempo?',
      certas: ['Perda de audição, que pode ser permanente'],
      erradas: [
        'A audição melhora com o treino',
        'Nada, o ouvido se acostuma sem problemas',
        'A música fica mais grave para sempre',
        'A caixa de som passa a gastar menos energia',
      ],
      porque: 'Sons acima de 85 dB por longos períodos podem lesionar o ouvido. Cuide do volume do fone também!',
    }),
  ],

  'Leitor de Cartão SD': [
    mc({
      d: 1,
      pesquise: 'Pesquise para que serve um leitor de cartão SD.',
      pergunta: 'Para que serve um leitor de cartão SD no computador?',
      certas: ['Ler e gravar arquivos de cartões de memória'],
      erradas: [
        'Aumentar a memória RAM',
        'Deixar a internet mais rápida',
        'Imprimir fotos',
        'Carregar a bateria do celular',
      ],
      porque: 'Com o leitor você passa fotos e vídeos da câmera (ou drone) para o computador.',
    }),
    vf({
      d: 2,
      pesquise: 'Pesquise onde os cartões de memória são usados e o que é um adaptador de microSD.',
      afirmacoes: [
        ['Câmeras, drones e alguns celulares usam cartão de memória.', true],
        ['Com um adaptador, dá para usar um cartão microSD num leitor de SD comum.', true],
        ['O leitor de cartão SD serve para aumentar a memória RAM.', false],
        ['O cartão SD perde os arquivos quando é tirado da câmera.', false],
      ],
      porque: 'O cartão usa memória flash: guarda tudo mesmo sem energia.',
    }),
    ordem({
      d: 3,
      pesquise: 'Pesquise o tamanho físico dos cartões CompactFlash, SD, miniSD e microSD.',
      pergunta: 'Ordene os cartões do MAIOR para o MENOR (tamanho físico).',
      itens: ['CompactFlash', 'SD', 'miniSD', 'microSD'],
      inicio: 'Maior',
      fim: 'Menor',
      porque: 'O microSD é do tamanho de uma unha — e mesmo assim pode guardar centenas de GB.',
    }),
    mc({
      d: 4,
      pesquise: 'Pesquise o que significam as classes de velocidade dos cartões (Classe 10, U1, U3, V30).',
      pergunta: 'Para gravar vídeo 4K numa câmera, qual cartão é o mais indicado?',
      certas: ['Um cartão U3 ou V30'],
      erradas: [
        'Um cartão Classe 2',
        'Qualquer cartão, a velocidade não importa',
        'O cartão com o adesivo mais colorido',
        'Um cartão sem classe de velocidade',
      ],
      porque: 'U3/V30 garantem gravação contínua de pelo menos 30 MB/s, o que vídeo 4K exige.',
    }),
    mc({
      d: 5,
      pesquise: 'Pesquise a diferença entre os padrões SD, SDHC e SDXC e a capacidade de cada um.',
      variantes: [
        { pergunta: 'Um cartão de 128 GB é de qual padrão?', corretas: ['SDXC'], incorretas: ['SDHC', 'SD (padrão original)', 'miniSD'] },
        { pergunta: 'Um cartão de 16 GB é de qual padrão?', corretas: ['SDHC'], incorretas: ['SDXC', 'SD (padrão original)', 'CompactFlash'] },
      ],
      certas: ['SDXC'],
      erradas: ['SDHC', 'SD (padrão original)', 'miniSD'],
      porque: 'SD: até 2 GB. SDHC: de 2 a 32 GB. SDXC: de 32 GB até 2 TB.',
    }),
  ],

  // ======================== NÍVEL 3 — REDES E INTERNET ========================

  'Roteador Wi-Fi': [
    mc({
      d: 1,
      pesquise: 'Pesquise para que serve um roteador Wi-Fi.',
      pergunta: 'Qual é a função de um roteador Wi-Fi?',
      certas: ['Distribuir a internet para vários aparelhos, com ou sem fio'],
      erradas: [
        'Guardar arquivos na nuvem',
        'Imprimir documentos',
        'Resfriar o computador',
        'Aumentar a memória do celular',
      ],
      porque: 'O roteador cria a rede da casa e encaminha os dados de cada aparelho.',
    }),
    vf({
      d: 2,
      pesquise: 'Pesquise o que atrapalha o sinal do Wi-Fi e quantos aparelhos podem se conectar.',
      afirmacoes: [
        ['Paredes grossas e distância podem enfraquecer o sinal do Wi-Fi.', true],
        ['Vários aparelhos podem usar o mesmo roteador ao mesmo tempo.', true],
        ['O sinal do Wi-Fi atravessa qualquer parede sem perder força.', false],
        ['O roteador Wi-Fi funciona mesmo sem energia elétrica.', false],
      ],
      porque: 'O Wi-Fi é uma onda de rádio: paredes, espelhos e distância enfraquecem o sinal.',
    }),
    mc({
      d: 3,
      pesquise: 'Pesquise a diferença entre as redes Wi-Fi de 2,4 GHz e de 5 GHz.',
      pergunta: 'Comparada à rede de 2,4 GHz, a rede de 5 GHz costuma…',
      certas: ['ser mais rápida, mas alcançar menos distância'],
      erradas: [
        'ser mais lenta e alcançar mais longe',
        'não funcionar em celulares',
        'não precisar de senha',
        'ser igual em tudo',
      ],
      porque: '5 GHz: mais velocidade, menos alcance. 2,4 GHz: mais alcance e atravessa melhor paredes.',
    }),
    pares({
      d: 4,
      pesquise: 'Pesquise os termos usados na configuração de uma rede Wi-Fi.',
      pergunta: 'Ligue cada termo ao seu significado.',
      lista: [
        ['SSID', 'Nome da rede Wi-Fi'],
        ['WPA2 / WPA3', 'Tipo de proteção (criptografia) da rede'],
        ['Senha do Wi-Fi', 'Chave para entrar na rede'],
        ['Repetidor', 'Aparelho que aumenta o alcance do sinal'],
      ],
      porque: 'Use sempre WPA2 ou WPA3 com uma senha forte para proteger a rede.',
    }),
    vf({
      d: 5,
      pesquise: 'Pesquise o que é o padrão Wi-Fi 6 e por que redes abertas ou com WEP são arriscadas.',
      afirmacoes: [
        ['Wi-Fi 6 é o nome comercial do padrão 802.11ax.', true],
        ['Numa rede Wi-Fi aberta (sem senha), outras pessoas podem tentar ver dados que não estejam protegidos.', true],
        ['Redes Wi-Fi com WEP são mais seguras que as com WPA3.', false],
        ['"Wi-Fi 6" significa que só 6 aparelhos podem se conectar.', false],
      ],
      porque: 'WEP é antigo e fácil de quebrar. Prefira WPA3 (ou WPA2) e evite digitar senhas em redes abertas.',
    }),
  ],

  Modem: [
    vf({
      d: 1,
      pesquise: 'Pesquise para que serve o modem na internet de casa.',
      afirmacoes: [
        ['O modem recebe o sinal da operadora e o converte para a rede da casa usar.', true],
        ['O modem e o roteador podem vir juntos no mesmo aparelho.', true],
        ['O modem é um programa instalado no celular.', false],
        ['O modem serve para imprimir documentos.', false],
      ],
      porque: 'O modem é a "ponte" entre o cabo da operadora e a rede da sua casa.',
    }),
    anagrama({
      d: 2,
      pesquise: 'Pesquise de quais duas palavras vem o nome "modem".',
      pergunta: 'O nome "modem" junta MOdulador e ______. Monte a palavra que falta.',
      palavra: 'DEMODULADOR',
      porque: 'MOdulador + DEModulador: o modem converte o sinal nos dois sentidos (enviar e receber).',
    }),
    mc({
      d: 3,
      pesquise: 'Pesquise a diferença entre modem e roteador.',
      pergunta: 'Qual é a diferença entre modem e roteador?',
      certas: ['O modem traz a internet da operadora; o roteador distribui ela para os aparelhos'],
      erradas: [
        'São exatamente a mesma coisa',
        'O roteador traz a internet da operadora; o modem só faz o Wi-Fi',
        'O modem é só para celular e o roteador só para computador',
        'O roteador guarda os sites que você visitou',
      ],
      porque: 'Muitas operadoras entregam um aparelho que faz as duas funções, mas elas são diferentes.',
    }),
    pares({
      d: 4,
      pesquise: 'Pesquise os tipos de conexão de internet que chegam às casas.',
      pergunta: 'Ligue cada tipo de conexão à sua descrição.',
      lista: [
        ['Fibra óptica', 'Sinal de luz por um fio de vidro ou plástico'],
        ['Cabo coaxial', 'Sinal elétrico pelo mesmo tipo de cabo da TV a cabo'],
        ['ADSL', 'Usa a linha do telefone fixo'],
        ['Satélite', 'Sinal que vem do espaço até uma antena'],
      ],
      porque: 'A fibra óptica é hoje a mais rápida e estável para uso doméstico.',
    }),
    escrita({
      d: 5,
      pesquise: 'Pesquise como se chama o aparelho que faz o papel de "modem" na internet por fibra óptica.',
      pergunta: 'Qual é a sigla desse aparelho da fibra óptica?',
      aceitas: ['ONT', 'ONU'],
      dica: 'Sigla de 3 letras',
      porque: 'Na fibra, a ONT (ou ONU) converte o sinal de luz em sinal elétrico para a rede da casa.',
    }),
  ],

  'Provedor de Internet (ISP)': [
    mc({
      d: 1,
      pesquise: 'Pesquise o que é um provedor de internet.',
      pergunta: 'O que é um provedor de internet (ISP)?',
      certas: ['A empresa que fornece a conexão de internet'],
      erradas: ['Um programa antivírus', 'Um tipo de cabo', 'Um site de busca', 'Uma peça do computador'],
      porque: 'Você contrata um provedor (operadora) para ter acesso à internet em casa.',
    }),
    escrita({
      d: 2,
      pesquise: 'Pesquise o que significa a sigla ISP em inglês.',
      pergunta: 'ISP significa Internet Service ______. Qual palavra (em inglês) falta?',
      aceitas: ['provider'],
      dica: 'Uma palavra em inglês',
      porque: 'ISP = Internet Service Provider (Provedor de Serviço de Internet).',
    }),
    slider({
      d: 3,
      pesquise: 'Pesquise a diferença entre megabits (Mb) e megabytes (MB). Dica: 1 byte = 8 bits.',
      min: 0,
      max: 60,
      passo: 0.5,
      unidade: 'MB/s',
      resposta: 12.5,
      variantes: [
        { pergunta: 'Um plano de 100 Mbps baixa, no máximo, quantos MB (megabytes) por segundo?', resposta: 12.5 },
        { pergunta: 'Um plano de 200 Mbps baixa, no máximo, quantos MB (megabytes) por segundo?', resposta: 25 },
        { pergunta: 'Um plano de 400 Mbps baixa, no máximo, quantos MB (megabytes) por segundo?', resposta: 50 },
        { pergunta: 'Um plano de 80 Mbps baixa, no máximo, quantos MB (megabytes) por segundo?', resposta: 10 },
      ],
      porque: 'Planos são vendidos em megabits. Para saber megabytes por segundo, divida por 8.',
    }),
    vf({
      d: 4,
      pesquise: 'Pesquise o que são download, upload e ping num teste de velocidade.',
      afirmacoes: [
        ['Download é receber dados da internet; upload é enviar dados.', true],
        ['Quanto menor o ping, menor o atraso da conexão.', true],
        ['Upload é o nome de baixar um jogo da internet.', false],
        ['Ping alto é melhor para jogar online.', false],
      ],
      porque: 'Ping (latência) é o tempo de ida e volta de um dado, em milissegundos: menor é melhor.',
    }),
    ordem({
      d: 5,
      pesquise: 'Pesquise o caminho que os dados fazem quando você abre um site pelo Wi-Fi de casa.',
      pergunta: 'Coloque em ordem o caminho do seu pedido até chegar ao site.',
      itens: ['Seu celular', 'Roteador Wi-Fi', 'Modem ou ONT', 'Provedor de internet', 'Servidor do site'],
      inicio: 'Sai daqui',
      fim: 'Chega aqui',
      porque: 'Os dados saem do aparelho, passam pela rede da casa, pela operadora e chegam ao servidor — e voltam!',
    }),
  ],

  'Cabo de Rede (Ethernet)': [
    vf({
      d: 1,
      pesquise: 'Pesquise para que serve o cabo de rede e como ele se compara ao Wi-Fi.',
      afirmacoes: [
        ['A conexão por cabo de rede costuma ser mais estável que o Wi-Fi.', true],
        ['O cabo de rede liga o computador ao roteador ou ao modem.', true],
        ['Cabo de rede e cabo HDMI são a mesma coisa.', false],
        ['O cabo de rede serve para levar energia da tomada ao monitor.', false],
      ],
      porque: 'Pelo cabo não há interferência de paredes e outras redes: menos quedas e menos atraso.',
    }),
    escrita({
      d: 2,
      pesquise: 'Pesquise o nome do conector das pontas do cabo de rede.',
      pergunta: 'Qual é o nome do conector do cabo de rede?',
      aceitas: ['RJ45', 'RJ 45'],
      dica: 'Duas letras e um número (ex: AB-12)',
      porque: 'O RJ-45 é parecido com o conector de telefone, mas maior (8 fios).',
    }),
    ordem({
      d: 3,
      pesquise: 'Pesquise a diferença entre kbps, Mbps e Gbps.',
      pergunta: 'Ordene as velocidades da MENOR para a MAIOR.',
      itens: ['500 kbps', '50 Mbps', '1 Gbps', '10 Gbps'],
      inicio: 'Menor',
      fim: 'Maior',
      porque: '1 Gbps = 1000 Mbps e 1 Mbps = 1000 kbps.',
    }),
    pares({
      d: 4,
      pesquise: 'Pesquise a velocidade máxima de cada categoria de cabo de rede (Cat5, Cat5e, Cat6a, Cat8).',
      pergunta: 'Ligue cada categoria de cabo à velocidade máxima que ela suporta.',
      lista: [
        ['Cat5', '100 Mbps'],
        ['Cat5e', '1 Gbps'],
        ['Cat6a', '10 Gbps'],
        ['Cat8', '25 a 40 Gbps (distâncias curtas)'],
      ],
      porque: 'Categorias maiores suportam velocidades maiores. Hoje o mínimo recomendado é Cat5e.',
    }),
    slider({
      d: 5,
      pesquise: 'Pesquise a distância máxima recomendada para um cabo de rede de par trançado sem repetidor.',
      pergunta: 'Qual é a distância máxima recomendada para um cabo de rede, em metros?',
      min: 0,
      max: 500,
      passo: 10,
      unidade: 'metros',
      resposta: 100,
      porque: 'Até 100 metros o sinal chega com qualidade. Acima disso é preciso um switch ou repetidor no meio.',
    }),
  ],

  'Endereço IP': [
    mc({
      d: 1,
      pesquise: 'Pesquise para que serve um endereço IP.',
      pergunta: 'Para que serve o endereço IP?',
      certas: ['Identificar um aparelho numa rede, como o endereço de uma casa'],
      erradas: [
        'Guardar senhas',
        'Deixar a internet mais rápida',
        'Proteger contra vírus',
        'Mostrar a hora certa',
      ],
      porque: 'Sem endereço, os dados não saberiam para qual aparelho ir.',
    }),
    vf({
      d: 2,
      pesquise: 'Pesquise o formato de um endereço IPv4 (ex: 192.168.0.10).',
      afirmacoes: [
        ['Um endereço IPv4 é formado por 4 números separados por pontos.', true],
        ['Em um IPv4, cada um dos 4 números vai de 0 a 255.', true],
        ['O endereço 192.168.0.300 é um IPv4 válido.', false],
        ['Um endereço IP é formado só por letras.', false],
      ],
      porque: 'Cada parte do IPv4 tem 8 bits, então vai de 0 a 255.',
    }),
    escrita({
      d: 3,
      pesquise: 'Pesquise o que é DNS e o que ele faz com os nomes dos sites.',
      pergunta: 'Qual é a sigla do sistema que traduz nomes de sites (como escola.com.br) em endereços IP?',
      aceitas: ['DNS'],
      dica: 'Sigla de 3 letras',
      porque: 'O DNS funciona como uma "agenda de contatos" da internet: nome → endereço IP.',
    }),
    mc({
      d: 4,
      pesquise: 'Pesquise quais números podem aparecer em cada parte de um endereço IPv4.',
      pergunta: 'Qual destes é um endereço IPv4 VÁLIDO?',
      certas: ['192.168.1.20', '10.0.0.5', '172.16.254.1', '8.8.8.8'],
      erradas: ['192.168.1.256', '10.0.0', '300.1.1.1', '192.168.1.2.3', '1A.2B.3C.4D'],
      porque: 'Precisa ter exatamente 4 números, cada um entre 0 e 255.',
    }),
    vf({
      d: 5,
      pesquise: 'Pesquise a diferença entre IP público e IP privado, e por que o IPv6 foi criado.',
      afirmacoes: [
        ['Endereços como 192.168.x.x são privados: funcionam dentro da rede local.', true],
        ['O IPv6 foi criado porque os endereços IPv4 estavam acabando.', true],
        ['Cada aparelho da sua casa sempre aparece na internet com um IP público diferente.', false],
        ['O IPv6 tem menos endereços possíveis que o IPv4.', false],
      ],
      porque: 'Em casa, vários aparelhos com IP privado costumam sair para a internet pelo mesmo IP público do roteador.',
    }),
  ],

  'Nuvem (Cloud)': [
    vf({
      d: 1,
      pesquise: 'Pesquise o que significa guardar arquivos "na nuvem".',
      afirmacoes: [
        ['Arquivos "na nuvem" ficam guardados em servidores de empresas, em outro lugar.', true],
        ['Normalmente é preciso internet para acessar os arquivos da nuvem.', true],
        ['A nuvem fica literalmente dentro das nuvens do céu.', false],
        ['Arquivos na nuvem ficam guardados só dentro do seu computador.', false],
      ],
      porque: '"Nuvem" é só um apelido para computadores (servidores) de empresas, acessados pela internet.',
    }),
    mc({
      d: 2,
      pesquise: 'Pesquise exemplos de serviços de armazenamento em nuvem.',
      pergunta: 'Qual destes é um serviço de armazenamento em nuvem?',
      certas: ['Google Drive', 'OneDrive', 'Dropbox', 'iCloud'],
      erradas: ['Pen drive', 'HD externo', 'Memória RAM', 'Cartão SD', 'Gabinete'],
      porque: 'Pen drive, HD e cartão são armazenamentos físicos que ficam com você — não na nuvem.',
    }),
    anagrama({
      d: 3,
      pesquise: 'Pesquise como se chama, em inglês, a cópia de segurança dos arquivos.',
      pergunta: 'Monte o nome da cópia de segurança dos arquivos.',
      palavra: 'BACKUP',
      porque: 'Fazer backup é guardar uma cópia para não perder nada se o computador quebrar.',
    }),
    pares({
      d: 4,
      pesquise: 'Pesquise exemplos de serviços na nuvem: armazenamento, streaming, e-mail e documentos online.',
      pergunta: 'Ligue cada serviço ao que ele faz.',
      lista: [
        ['Google Drive', 'Guardar arquivos'],
        ['Spotify', 'Ouvir músicas por streaming'],
        ['Gmail', 'Enviar e receber e-mails'],
        ['Google Docs', 'Escrever textos online'],
        ['Netflix', 'Assistir filmes e séries por streaming'],
      ],
      quantidade: 4,
      porque: 'Muita coisa que usamos no dia a dia roda na nuvem, não no nosso aparelho.',
    }),
    mc({
      d: 5,
      pesquise: 'Pesquise a regra de backup 3-2-1.',
      pergunta: 'O que diz a regra de backup 3-2-1?',
      certas: ['Ter 3 cópias dos dados, em 2 tipos de mídia diferentes, com 1 cópia fora de casa'],
      erradas: [
        'Fazer backup 3 vezes por dia, 2 dias por semana e 1 vez por mês',
        'Usar 3 pen drives, 2 HDs e 1 celular ao mesmo tempo',
        'Guardar só 1 cópia para não ocupar espaço',
        'Apagar os arquivos originais depois de 3 dias',
      ],
      porque: 'Com 3 cópias em lugares diferentes, é muito difícil perder tudo de uma vez.',
    }),
  ],

  Firewall: [
    mc({
      d: 1,
      pesquise: 'Pesquise para que serve um firewall.',
      pergunta: 'Qual é a função de um firewall?',
      certas: ['Filtrar o tráfego da rede e bloquear acessos não autorizados'],
      erradas: [
        'Deixar o Wi-Fi mais rápido',
        'Guardar senhas',
        'Apagar fotos antigas',
        'Carregar a bateria do notebook',
      ],
      porque: 'O firewall funciona como um porteiro: decide o que pode entrar e sair da rede.',
    }),
    vf({
      d: 2,
      pesquise: 'Pesquise a diferença entre firewall e antivírus.',
      afirmacoes: [
        ['Firewall e antivírus são proteções diferentes que se complementam.', true],
        ['Um firewall pode ser um programa ou um aparelho de rede.', true],
        ['Firewall e antivírus são exatamente a mesma coisa.', false],
        ['Com o firewall ligado, não é preciso ter cuidado com links suspeitos.', false],
      ],
      porque: 'O firewall controla conexões; o antivírus procura programas maliciosos. Nenhum substitui o cuidado do usuário.',
    }),
    anagrama({
      d: 3,
      pesquise: 'Pesquise o nome do golpe em que criminosos mandam mensagens falsas para roubar senhas (vem de "fishing", pescar).',
      pergunta: 'Monte o nome desse golpe.',
      palavra: 'PHISHING',
      porque: 'No phishing o golpista "pesca" dados com e-mails, sites e mensagens falsas.',
    }),
    pares({
      d: 4,
      pesquise: 'Pesquise os principais tipos de ameaça digital.',
      pergunta: 'Ligue cada termo à sua descrição.',
      lista: [
        ['Vírus', 'Programa que se espalha infectando arquivos'],
        ['Phishing', 'Mensagem falsa para roubar dados'],
        ['Ransomware', 'Sequestra arquivos e pede resgate'],
        ['Spyware', 'Espiona o que você faz no aparelho'],
        ['Firewall', 'Barreira que filtra o tráfego da rede'],
      ],
      quantidade: 4,
      porque: 'Conhecer as ameaças é o primeiro passo para se proteger delas.',
    }),
    mc({
      d: 5,
      pesquise: 'Pesquise o que é autenticação em dois fatores (2FA).',
      pergunta: 'Por que ativar a verificação em duas etapas (2FA) protege sua conta?',
      certas: ['Porque além da senha é preciso outro código, então só a senha roubada não basta'],
      erradas: [
        'Porque ela troca a senha sozinha todo dia',
        'Porque ela remove todos os vírus do computador',
        'Porque ela deixa a internet mais rápida',
        'Porque ela apaga a conta se alguém errar a senha',
      ],
      porque: 'Mesmo que alguém descubra sua senha, ainda precisaria do código do seu celular.',
    }),
  ],
};

module.exports = { BANCO_DE_QUESTOES };
